name: Cloudflare Pages Deploy

on: [push]

jobs:
  publish:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node_version: 20
      - run: npm i
      - run: npm run build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: ixy-website
          directory: ./out
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
